version: "3.1"

services:
  stock2u-api:
    image: openjdk:17
    container_name: stock2u-api
    volumes:
      - ./build/libs/stock2u-api-0.0.1-SNAPSHOT.jar:/app.jar
    env_file:
      - .env
    command: ["java", "-jar", "/app.jar"]
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
