server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
        http-only: true
    context-path: /api

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    stack:
      auto: false


spring:
  profiles:
    group:
      local:
        - db-local
        - aws-dev
      dev:
        - db-local
        - aws-dev
      prod:
        - db-prod
    active:
      - local
  config:
    import: externel.yaml
    location: classpath:/config
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        regitstration:
          kakao:
            client-id: ${KAKAO_REST_API}
            client-name: Kakao
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: account_email
            redirect-uri: http://localhost:3000/auth/oauth-redirect
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.data.convert: ERROR
    org.hibernate: DEBUG
    org.springframework.beans.factory.support: INFO
    com.zaxxer.hikari: INFO
    io.netty: INFO
    org.springframework.context.annotation: INFO
    org.hibernate.type.descriptor.sql: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.hql.internal.ast: WARN
    org.mongodb.driver.cluster: ERROR
    org.mongodb.driver.protocol: ERROR
    org.springframework.data.redis.core.RedisConnectionUtils: WARN
    io.lettuce.core.protocol: WARN
    com.amazonaws.util.EC2MetadataUtils: ERROR
    com.amazonaws.internal.EC2ResourceFetcher: ERROR
    org.apache.http.wire: WARN
# local 환경
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: ${HOME_JDBC_URL}
      username: ${HOME_MARIADB_USERNAME}
      password: ${HOME_MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  data:
    mongodb:
      host: ${HOME_MONGO_HOST}
      port: 27017
      database: local
      password: ${HOME_MONGO_PASSWORD}
      username: ${HOME_MONGO_USERNAME}
      authentication-database: admin
  redis:
    host: ${HOME_REDIS_HOST}
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: stock2u:session
    timeout: 1h


# dev 환경
---
spring:
  config:
    activate:
      on-profile: "dev"
  session:
    store-type: redis
    redis:
      namespace: stock2u:session
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: ${HOME_JDBC_URL}
      username: ${HOME_MARIADB_USERNAME}
      password: ${HOME_MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    mongodb:
      uri: ${HOME_MONGO_URI}
      database: "stock2u"
      port: 27017
      password: ${HOME_MONGO_PASSWORD}
      username: ${HOME_MONGO_USERNAME}
  redis:
    host: ${HOME_REDIS_HOST}
    port: 6379

---

# prod 환경
spring:
  config:
    activate:
      on-profile: "prod"
  session:
    store-type: redis
    redis:
      namespace: stock2u:session
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: ${HOME_JDBC_URL}
      username: ${HOME_MARIADB_USERNAME}
      password: ${HOME_MARIADB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  data:
    mongodb:
      uri: ${HOME_MONGO_URI}
      database: "stock2u"
      host: ${HOME_MONGO_HOST}
      port: 27017
      password: ${HOME_MONGO_PASSWORD}
      username: ${HOME_MONGO_USERNAME}
  redis:
    host: ${HOME_REDIS_HOST}
    port: 6379
